# Crear un sistema operativo con node ya instalado
# ==== COPIA DE DEPENDENCIAS ====
FROM node:21-alpine3.20 AS deps

WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./

RUN npm install && npm audit fix


# ==== CONSTRUCCION DE LA APLICACION ====
FROM node:21-alpine3.20 as build

WORKDIR /usr/src/app

COPY --from=deps /usr/src/app/node_modules ./node_modules

COPY . .

RUN npm run build

# Esto solo mantiene las dependencias de producción, y hace q sea el proyecto mas ligero
RUN npm ci -f --only=production && npm cache clean --force



# ==== CREACION DE LA IMAGEN FINAL ====
FROM node:21-alpine3.20 as prod

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/node_modules ./node_modules
# COPY --from=build /usr/src/app/package.json ./package.json

ENV NODE_ENV=production

# Para protecicon de archivos con este usuario
USER node

EXPOSE 8000

CMD ["node", "dist/main.js"]
