services:
  pv-products-database:
    image: postgres
    container_name: pv_products_database
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data