services:
  pv-auth-db-postgres:
    image: postgres:13.5
    container_name: database
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    
    ports:
      - 5433:5432
    
    volumes:
      - ./postgres:/var/lib/postgresql/data